# Generated by Django 4.2.6 on 2024-02-28 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=64)),
                ('description', models.CharField(max_length=400)),
                ('path', models.TextField()),
                ('create_date', models.DateTimeField(verbose_name='date created')),
            ],
        ),
    ]
